title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://sparkz-nz.github.io/pytest

aux_links:
  Sparkkz Maker Notes: https://sparkz-nz.github.io/
